### PR TITLE
Fix MATLAB tests

### PR DESCRIPTION
**Pull request by ludvigak**
Simple fixes to get rid of errors in Matlab test suite

- Add Chebfun as submodule dependency
- Removed section breaks that split up tests
- Removed hardcoded file path
- Set default edge color in @surfer/plot to black (?)
- Create `ndeg=1` in `test_surf_lap`. It seemed like the right value.

NOTE: There are more hard-coded paths in `demo/` that point to `~/git/fmm3dbie` and `~/git/surface-hps`

### CODE REVIEW

**Comment by ludvigak** [comment]
To test the branch you'll have to run `git submodule update --init --recursive` to get the new submodule checked out

**Comment by ahbarnett** [comment]
grepping matlab directory I only see `chebpts` and `barymat` used from chebfun pkg - if that's all, can't we remove chebfun as a dependency?

**Comment by ludvigak** [comment]
First I tried copying in only legpts and chebpts, but the latter called chebtech1, at which point I gave up and pulled in all of chebfun. You can probably untangle the dependencies with some patience though.

**Comment by mrachh** [comment]
We are on it to remove those dependencies. Thanks for these catches Ludvig, we can merge them in, once the dependencies are removed.

**Comment by ahbarnett** [comment]
I forgot `legpts`. Yes, keep chebfun as dependency for next week.

**Comment by mrachh** [comment]
Hi Ludvig, can you remove the chebfun dependency and update the pull request? I think I should've successfully removed those dependencies..

**Comment by ludvigak** [comment]
Had to do a few fixes, but now all tests pass without Chebfun

**Review by mrachh — APPROVED** [review]
Thanks Ludvig!

**Pull request merged**
